---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mission

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yml
  - serviceaccount.yml
  - configmap.yml
  - deployment.yml
  - service.yml
  - networkpolicy.yml
  - hpa.yml
