---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mission-processor-sa
  namespace: mission
  labels:
    app.kubernetes.io/name: mission-data-processor
    app.kubernetes.io/part-of: mdi-sovereign
  annotations:
    # AWS: IRSA annotation (overridden in aws-sovereign overlay)
    # Azure: Workload Identity annotation (overridden in azure-allied overlay)
    eks.amazonaws.com/role-arn: ""
automountServiceAccountToken: false
